apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo-deployment
  labels:
    app: app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - name: app-demo
        image: 207061669504.dkr.ecr.us-east-1.amazonaws.com/app-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000