apiVersion: v1
kind: Service
metadata:
  name: app-demo-staging-service
spec:
  selector:
    app: app-demo-staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  # type: ClusterIP
  type: LoadBalancer